\context ChordNames
	\chords {
		\set majorSevenSymbol = \markup { "maj7" }
		\set chordChanges = ##t

		% intro
		d1 d1

		% hazme un instrumento de tu paz...
		d1 | d1 | d1 a1 |
		e1:m | a1 |
		g2 a2 | d1

		% hazme un instrumento de tu paz...
		d1 | d1 | d1 a1 |
		e1:m | a1 |
		g2 a2 | d2 d2:7 |

		% maestro...
		g1 | d2 b2:m |
		e2:m a2 | d2 d2:7 |
		g1 d1 |
		e1:7 a1 |
		a4:7 s4

		% hazme un instrumento de tu paz...
		d1 | d1 | d1 a1 |
		e1:m | a1 |
		g2 a2 | d2 d2:7 |

		% maestro...
		g1 | d2 b2:m |
		e2:m a2 | d2 d2:7 |
		g1 d1 |
		e1:7 a1 |
		a4:7 s4

		% hazme un instrumento de tu paz...
		d1 | d1 |
	}
